-- ==============================================================================
-- Neon PostgreSQL Schema for GAMA / L'Conq
-- Fully compatible with Serverless Neon PostgreSQL
-- ==============================================================================

-- 1. Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Auth Schema Compatibility (Emulates auth for clean cross-compatibility)
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
  id text PRIMARY KEY,
  email text UNIQUE,
  raw_user_meta_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- auth.uid() function shim for PostgreSQL / Neon
CREATE OR REPLACE FUNCTION auth.uid() RETURNS text AS $$
BEGIN
  RETURN COALESCE(
    current_setting('request.jwt.claim.sub', true),
    current_setting('app.current_user_id', true)
  );
END;
$$ LANGUAGE plpgsql STABLE;

-- 3. Profiles Table (Supports both UUIDs and custom IDs like Massar codes)
CREATE TABLE IF NOT EXISTS public.profiles (
  id text PRIMARY KEY,
  name text,
  email text,
  phone text,
  city text,
  role text DEFAULT 'student',
  tier text DEFAULT 'freemium',
  xp integer DEFAULT 0,
  streak integer DEFAULT 0,
  rank integer,
  total_students integer DEFAULT 1200,
  school text,
  class_id text,
  joined timestamp with time zone DEFAULT timezone('utc'::text, now()),
  subscription jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Helper: Check if current user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
SECURITY DEFINER SET search_path = public
LANGUAGE plpgsql AS $$
DECLARE
  curr_uid text;
  user_role text;
BEGIN
  curr_uid := auth.uid();
  IF curr_uid IS NULL THEN
    RETURN false;
  END IF;
  SELECT role INTO user_role FROM public.profiles WHERE id = curr_uid;
  RETURN (user_role = 'admin');
END;
$$;

-- 4. Config Table
CREATE TABLE IF NOT EXISTS public.config (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 5. Exams Table
CREATE TABLE IF NOT EXISTS public.exams (
  id text PRIMARY KEY,
  name text NOT NULL,
  school text,
  level text,
  year text,
  tier text DEFAULT 'freemium',
  questions jsonb DEFAULT '[]'::jsonb,
  pdf_url text,
  is_active boolean DEFAULT true,
  is_archived boolean DEFAULT false,
  date_added timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 6. Classes Table
CREATE TABLE IF NOT EXISTS public.classes (
  id text PRIMARY KEY,
  name text NOT NULL,
  level text,
  students jsonb DEFAULT '[]'::jsonb,
  student_count integer DEFAULT 0,
  competitions jsonb DEFAULT '[]'::jsonb,
  competition_grades jsonb DEFAULT '{}'::jsonb,
  controls jsonb DEFAULT '[]'::jsonb,
  grades jsonb DEFAULT '{}'::jsonb,
  homework jsonb DEFAULT '{}'::jsonb,
  language text DEFAULT 'fr',
  program jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 7. Lessons Table
CREATE TABLE IF NOT EXISTS public.lessons (
  id text PRIMARY KEY,
  title text NOT NULL,
  subject text,
  chapter_number text,
  teacher text,
  phone text,
  schools jsonb DEFAULT '[]'::jsonb,
  level text,
  doc_type text DEFAULT 'course',
  content jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  is_archived boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 8. Activation Codes Table
CREATE TABLE IF NOT EXISTS public.activation_codes (
  code text PRIMARY KEY,
  plan_id text,
  is_used boolean DEFAULT false,
  used_by text,
  used_at timestamp with time zone,
  batch_name text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 9. Progress Table (SRS/FSRS Spaced Repetition)
CREATE TABLE IF NOT EXISTS public.progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  question_id text NOT NULL,
  difficulty double precision,
  stability double precision,
  repetitions integer,
  ease_factor double precision,
  last_review_date timestamp with time zone,
  next_review_date timestamp with time zone,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, question_id)
);

-- 10. Mock History Table
CREATE TABLE IF NOT EXISTS public.mock_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  exam_id text NOT NULL,
  exam_name text,
  school text,
  score double precision,
  max_score integer,
  pct double precision,
  correct_count integer,
  wrong_count integer,
  empty_count integer,
  mode text,
  date timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 11. Activity Table (Streaks / Daily Tracking)
CREATE TABLE IF NOT EXISTS public.activity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  count integer DEFAULT 1,
  UNIQUE(user_id, date)
);

-- 12. Extraction Tasks (AI Document Processing Queue)
CREATE TABLE IF NOT EXISTS public.extraction_tasks (
  id text PRIMARY KEY,
  file_name text NOT NULL,
  file_type text,
  page_count integer DEFAULT 1,
  provider text DEFAULT 'gemini',
  model text,
  status text DEFAULT 'pending',
  progress_percent integer DEFAULT 0,
  progress_message text,
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  error_message text,
  result_json jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  completed_at timestamp with time zone
);

-- 13. High Performance Indexes
CREATE INDEX IF NOT EXISTS idx_profiles_xp ON public.profiles(xp DESC);
CREATE INDEX IF NOT EXISTS idx_progress_user_id ON public.progress(user_id);
CREATE INDEX IF NOT EXISTS idx_progress_user_next_review ON public.progress(user_id, next_review_date);
CREATE INDEX IF NOT EXISTS idx_mock_history_user_id ON public.mock_history(user_id);
CREATE INDEX IF NOT EXISTS idx_mock_history_user_date ON public.mock_history(user_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_activity_user_id ON public.activity(user_id);
CREATE INDEX IF NOT EXISTS idx_exams_active_school ON public.exams(is_active, is_archived, school, year);
CREATE INDEX IF NOT EXISTS idx_exams_date_added ON public.exams(date_added DESC);
CREATE INDEX IF NOT EXISTS idx_lessons_active_level ON public.lessons(is_active, level, subject);
CREATE INDEX IF NOT EXISTS idx_lessons_created_at ON public.lessons(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_classes_created_at ON public.classes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_extraction_tasks_status ON public.extraction_tasks(status, created_at DESC);

-- 14. Views
CREATE OR REPLACE VIEW public.exams_metadata AS
SELECT 
  id,
  name,
  school,
  level,
  year,
  tier,
  pdf_url,
  is_active,
  is_archived,
  date_added,
  updated_at,
  COALESCE(jsonb_array_length(questions), 0) AS questions_count
FROM public.exams;

-- 15. Stored Procedures & RPC Functions
CREATE OR REPLACE FUNCTION public.get_all_profiles()
RETURNS SETOF public.profiles
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY SELECT * FROM public.profiles ORDER BY joined DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_leaderboard()
RETURNS TABLE (
  name text,
  xp integer,
  streak integer,
  tier text
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT profiles.name, profiles.xp, profiles.streak, profiles.tier
  FROM public.profiles
  WHERE (profiles.role IS DISTINCT FROM 'admin') AND (LOWER(profiles.name) != 'directeur')
  ORDER BY profiles.xp DESC
  LIMIT 100;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_user(uid text)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  DELETE FROM public.profiles WHERE id = uid;
  DELETE FROM auth.users WHERE id = uid;
END;
$$;

CREATE OR REPLACE FUNCTION public.redeem_code(input_code text, user_name_or_email text, user_id text)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  code_row record;
  plans_json jsonb;
  plan_item jsonb;
  plan_found boolean := false;
  plan_duration integer;
  sub_end_date timestamp with time zone;
BEGIN
  SELECT * INTO code_row FROM public.activation_codes WHERE upper(code) = upper(input_code);
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Code d''activation invalide. Veuillez vérifier la saisie.';
  END IF;

  IF code_row.is_used THEN
    RAISE EXCEPTION 'Ce code a déjà été utilisé.';
  END IF;

  SELECT value INTO plans_json FROM public.config WHERE key = 'plans';
  IF FOUND AND plans_json ? 'plans' THEN
    FOR plan_item IN SELECT jsonb_array_elements(plans_json->'plans') LOOP
      IF plan_item->>'id' = code_row.plan_id THEN
        plan_found := true;
        plan_duration := (plan_item->>'durationDays')::integer;
      END IF;
    END LOOP;
  ELSE
    plan_found := true;
    plan_duration := 365;
  END IF;

  UPDATE public.activation_codes
  SET is_used = true,
      used_by = user_name_or_email,
      used_at = now()
  WHERE upper(code) = upper(input_code);

  sub_end_date := now() + (plan_duration || ' days')::interval;

  UPDATE public.profiles
  SET tier = 'premium',
      subscription = jsonb_build_object(
        'planId', code_row.plan_id,
        'status', 'active',
        'startDate', now(),
        'endDate', sub_end_date
      )
  WHERE id = user_id;

  RETURN jsonb_build_object(
    'success', true,
    'planId', code_row.plan_id,
    'durationDays', plan_duration
  );
END;
$$;

-- 16. Assets Table (For storing uploaded figures, photos, and files)
CREATE TABLE IF NOT EXISTS public.assets (
  id text PRIMARY KEY,
  path text UNIQUE NOT NULL,
  data text NOT NULL,
  mime_type text DEFAULT 'image/png',
  size bigint DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
CREATE INDEX IF NOT EXISTS idx_assets_path ON public.assets(path);

-- 17. Login Logs Table
CREATE TABLE IF NOT EXISTS public.login_logs (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  logged_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  ip text,
  user_agent text
);
CREATE INDEX IF NOT EXISTS idx_login_logs_user_id ON public.login_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_login_logs_logged_at ON public.login_logs(logged_at DESC);


